name: Horizons
description: Horizons template for Jekyll
paginate: 10
baseurl: "/dpjedi-stage" # the subpath of your site, e.g. /blog
url: "https://adam3smith.github.io" # the base hostname & protocol for your site
